version: '3.8'
services:
  inmo-smart-app:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - nodemodules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: bash -c "npm install && npm start"
volumes:
  nodemodules:
